[project]
authors = ["Emanuele Giacomini <giacomini@diag.uniroma1.it>"]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "multi_os_compatibility_check"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
eigen = ">=3.4.0,<4"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
